<a href="https://colab.research.google.com/github/AbrahamKong/CMPE258-Tensor_Operations_Practice/blob/main/Tensor_Operations_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at **`tf.dtypes.DType`**.


you can never update the contents of a tensor, only create a new one.

# Basic

### Scalar/Rank-0 Tensor

A scalar contains a single value, and no "axes".

In [ ]:
tensor_rank_0 = tf.constant(4)
print(tensor_rank_0)

tf.Tensor(4, shape=(), dtype=int32)


### Vector/Rank-1 Tensor

A vector with 1 axis and work like a "List"

In [ ]:
tensor_rank_1 = tf.constant([2.0, 3.0, 4.0])
print(tensor_rank_1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### Matrix/Rank-2 Tensor

In [ ]:
tensor_rank_2 = tf.constant([[1, 2], 
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(tensor_rank_2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


### Tensor with mroe Axes

In [ ]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


### Visualizing Tensor

You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:

In [ ]:
np.array(tensor_rank_2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)