<a href="https://colab.research.google.com/github/AbrahamKong/CMPE258-Tensor_Operations_Practice/blob/main/Tensor_Operations_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at **`tf.dtypes.DType`**.


you can never update the contents of a tensor, only create a new one.

# Basic

### Scalar/Rank-0 Tensor

A scalar contains a single value, and no "axes".

In [2]:
tensor_rank_0 = tf.constant(4)
print(tensor_rank_0)

tf.Tensor(4, shape=(), dtype=int32)


### Vector/Rank-1 Tensor

A vector with 1 axis and work like a "List"

In [3]:
tensor_rank_1 = tf.constant([2.0, 3.0, 4.0])
print(tensor_rank_1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### Matrix/Rank-2 Tensor

In [4]:
tensor_rank_2 = tf.constant([[1, 2], 
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(tensor_rank_2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


### Tensor with mroe Axes

In [5]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
tensor_rank_3 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(tensor_rank_3)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


### Visualizing Tensor

You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:

In [6]:
np.array(tensor_rank_2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [7]:
tensor_rank_2.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

### Basic Math on Tensor

In [8]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [9]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [10]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


### Shapes

Tensors have shapes.  Some vocabulary:

* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes.  A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product shape vector.


In [11]:
tensor_rank_4 = tf.zeros([3, 2, 4, 5])

In [12]:
print("Type of every element:", tensor_rank_4.dtype)
print("Number of axes:", tensor_rank_4.ndim)
print("Shape of tensor:", tensor_rank_4.shape)
print("Elements along axis 0 of tensor:", tensor_rank_4.shape[0])
print("Elements along the last axis of tensor:", tensor_rank_4.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(tensor_rank_4).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [13]:
tensor=tf.constant([
                    [[0, 1, 2, 3, 4], 
                     [5, 6, 7, 8, 9]], 
                    [[10, 11, 12, 13, 14], 
                     [15, 16, 17, 18, 19]], 
                    [[20, 21, 22, 23, 24], 
                     [25, 26, 27, 28, 29]],])

In [15]:
newtensor=tf.reshape(tensor, [3, -1])

In [16]:
newtensor.shape

TensorShape([3, 10])

## Indexing

### Single-axis indexing

TensorFlow follows standard Python indexing rules.

* indexes start at `0`
* negative indices count backwards from the end
* colons, `:`, are used for slices: `start:stop:step`


In [18]:
tensor_rank_1 = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


**Indexing** with a scalar removes the axis:

In [19]:
print("First:", tensor_rank_1[0].numpy())
print("Second:", tensor_rank_1[1].numpy())
print("Last:", tensor_rank_1[-1].numpy())

First: 0
Second: 1
Last: 34


Indexing with a `:` slice keeps the axis:

In [ ]:
print("Everything:", tensor_rank_1[:].numpy())
print("Before 4:", tensor_rank_1[:4].numpy())
print("From 4 to the end:", tensor_rank_1[4:].numpy())
print("From 2, before 7:", tensor_rank_1[2:7].numpy())
print("Every other item:", tensor_rank_1[::2].numpy())
print("Reversed:", tensor_rank_1[::-1].numpy())

### Multi-axis indexing

Higher rank tensors are indexed by passing multiple indices.

The exact same rules as in the single-axis case apply to each axis independently.

In [ ]:
print(tensor_rank_2.numpy())

Passing an integer for each index, the result is a scalar.

In [ ]:
# Pull out a single value from a 2-rank tensor
print(tensor_rank_2[1, 1].numpy())

You can index using any combination of integers and slices:

In [ ]:
# Get row and column tensors
print("Second row:", tensor_rank_2[1, :].numpy())
print("Second column:", tensor_rank_2[:, 1].numpy())
print("Last row:", tensor_rank_2[-1, :].numpy())
print("First item in last column:", tensor_rank_2[0, -1].numpy())
print("Skip the first row:")
print(tensor_rank_2[1:, :].numpy(), "\n")

In [ ]:
print(tensor_rank_3[:, :, 4])

Read the [tensor slicing guide](https://tensorflow.org/guide/tensor_slicing) to learn how you can apply indexing to manipulate individual elements in your tensors.

## Manipulating Shapes

Reshaping a tensor is of great utility. 


In [ ]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

In [ ]:
# You can convert this object into a Python list, too
print(x.shape.as_list())

You can reshape a tensor into a new shape. The `tf.reshape` operation is fast and cheap as the underlying data does not need to be duplicated.

In [ ]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])

In [ ]:
print(x.shape)
print(reshaped.shape)

In [17]:
# s = tf.random.normal(shape=[11, 7, 5, 3])
# t = tf.random.normal(shape=[11, 7, 3, 2])
# e = tf.enisum('...ij, ...jk->...ik', s, t)

# e.shape

AttributeError: ignored

# Reference

[Introduction to Tensors](
https://www.tensorflow.org/guide/tensor)

[Tensor Colab](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/guide/tensor.ipynb)

[Tensor Baiscs Colab](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/customization/basics.ipynb)

[Enisum Video](https://www.youtube.com/watch?v=pkVwUVEHmfI)

[Pytorch Presentation](https://docs.google.com/presentation/d/13Oo5gXwcsoq9oMC4XriAyxkvgicatBxfI4cZzDhRyiE/edit#slide=id.p)

[Pytorch Colab](https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p1ch3/1_tensors.ipynb (Links to an external site.))

[TF-Coder User Journeys](https://github.com/google-research/tensorflow-coder/blob/master/UserJourneys.md)